(async()=>{
const O=String(window.SEVEN_PRINCE_ASSET_ORIGIN||'').replace(/\/+$/,'');
if(!O||O.includes('YOUR-CLOUDFLARE-SUBDOMAIN')){document.body.insertAdjacentHTML('beforeend','<div style="position:fixed;inset:20px;color:red;z-index:99">config.js의 Cloudflare Worker 주소를 설정하세요.</div>');return;}
const chapters=await fetch(`${O}/manifest`,{cache:'no-store'}).then(r=>{if(!r.ok)throw Error(`manifest ${r.status}`);return r.json()});
const pages={home:homePage,menu:menuPage,viewer:viewerPage,downloads:downloadPage};
let mode='comic',chapter='219',idx=0,token=0;
homeLogo.src=`${O}/asset/ui/home-logo.webp`;
function show(n){Object.values(pages).forEach(x=>x.classList.remove('active'));pages[n].classList.add('active');scrollTo(0,0)}
function buildMenu(){chocolateGrid.replaceChildren();const slots={5:'218',6:'219',7:'220'};if(mode==='download')slots[7]=null;for(let i=0;i<10;i++){const ch=slots[i],el=document.createElement(ch?'button':'div');el.className='choco-cell'+(ch?' active-cell':'');if(ch){el.type='button';el.textContent=mode==='comic'?`${ch}화 보기`:`${ch}화 다운로드`;el.onclick=()=>{chapter=ch;idx=0;if(mode==='comic'){render();show('viewer')}else{buildDownloads(ch);show('downloads')}}}chocolateGrid.append(el)}}
openComicMenu.onclick=()=>{mode='comic';buildMenu();show('menu')};openDownloadMenu.onclick=()=>{mode='download';buildMenu();show('menu')};document.querySelectorAll('[data-home]').forEach(b=>b.onclick=()=>show('home'));
function asset(f,download=false){return `${O}/${download?'download':'asset'}/${f.path}`}
function loadImage(url){return new Promise((res,rej)=>{const im=new Image();im.crossOrigin='anonymous';im.decoding='async';im.onload=()=>res(im);im.onerror=rej;im.src=url})}
async function render220(p){const t=++token;viewerImage.style.display='none';viewerImage.removeAttribute('src');viewerTileAssembly.style.display='block';let c=document.getElementById('viewerReassemblyCanvas');if(!c){c=document.createElement('canvas');c.id='viewerReassemblyCanvas';c.style.cssText='position:absolute;inset:0;width:100%;height:100%;pointer-events:none';viewerTileAssembly.append(c)}c.width=p.width;c.height=p.height;const x=c.getContext('2d',{alpha:false});x.fillStyle='#fff';x.fillRect(0,0,c.width,c.height);const ims=await Promise.all(p.tiles.map(async q=>[await loadImage(asset(q)),q]));if(t!==token||chapter!=='220')return;for(const [im,q] of ims)x.drawImage(im,q.x,q.y);fit(p.width,p.height)}
async function render(){const f=chapters[chapter][idx];if(chapter==='220'){await render220(f);return}++token;viewerTileAssembly.style.display='none';viewerImage.style.display='block';viewerImage.src=asset(f);viewerImage.onload=()=>fit(viewerImage.naturalWidth,viewerImage.naturalHeight)}
function fit(w,h){const vw=innerWidth,vh=innerHeight,s=Math.min(vw/w,vh/h);viewerArtwork.style.width=`${Math.round(w*s)}px`;viewerArtwork.style.height=`${Math.round(h*s)}px`}
function next(){if(idx<chapters[chapter].length-1){idx++;render()}}function prev(){if(idx>0){idx--;render()}}nextZone.onclick=next;prevZone.onclick=prev;addEventListener('resize',()=>{const f=chapters[chapter]?.[idx];if(!f)return;if(chapter==='220')fit(f.width,f.height);else if(viewerImage.naturalWidth)fit(viewerImage.naturalWidth,viewerImage.naturalHeight)});addEventListener('keydown',e=>{if(!viewerPage.classList.contains('active'))return;if(e.key==='ArrowLeft')next();if(e.key==='ArrowRight')prev();if(e.key==='Escape')show('home')});['contextmenu','dragstart','selectstart'].forEach(t=>viewerArtwork.addEventListener(t,e=>e.preventDefault()));
function buildDownloads(ch){const fs=chapters[ch];downloadTitle.textContent=`${ch}화`;downloadGrid.replaceChildren();for(const f of fs){const card=document.createElement('article');card.className='download-card';const im=document.createElement('img');im.loading='lazy';im.src=asset(f);const name=document.createElement('div');name.className='file-name';name.textContent=f.name;const a=document.createElement('a');a.className='file-download';a.href=asset(f,true);a.textContent='다운로드';a.download=f.name;card.append(im,name,a);downloadGrid.append(card)}}
downloadAll.onclick=async()=>{if(chapter==='220')return;for(const f of chapters[chapter]){const a=document.createElement('a');a.href=asset(f,true);a.download=f.name;document.body.append(a);a.click();a.remove();await new Promise(r=>setTimeout(r,400))}};
})();
