#!/usr/bin/env python3
"""Compare SentenceLab's current role model with collected UD gold analysis.

Input: data/web_corpus_bot/*.jsonl generated by auto_web_corpus_bot.py
Gold:  canonical S/V/O/C/M roles derived from the upstream UD dependency parse
Pred:  the newest compatible SentenceLab RoleNet checkpoint in artifacts/*role.pt
Output: artifacts/web_corpus_comparison.txt (plain-text TSV tables)

AMBIG gold tokens are intentionally excluded from accuracy calculations and are
reported separately. This prevents uncertain coordination labels from inflating
or unfairly lowering the model score.
"""
from __future__ import annotations

import argparse
import json
import re
import sys
from collections import Counter, defaultdict
from pathlib import Path

import torch

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "train"))

import train_ud_role as role_model

DATA_DIR = ROOT / "data" / "web_corpus_bot"
DEFAULT_OUT = ROOT / "artifacts" / "web_corpus_comparison.txt"
ROLE_NAMES = ["NONE", "S", "V", "O", "C", "M"]


def natural_key(path: Path):
    return [int(part) if part.isdigit() else part.lower() for part in re.split(r"(\d+)", path.name)]


def load_latest_compatible_model(explicit: str | None = None):
    if explicit:
        candidates = [Path(explicit)]
    else:
        candidates = sorted(ROOT.joinpath("artifacts").glob("*role.pt"), key=natural_key, reverse=True)
    if not candidates:
        raise SystemExit("no artifacts/*role.pt model checkpoint found")

    failures = []
    for path in candidates:
        if not path.is_absolute():
            path = (ROOT / path).resolve() if not path.exists() else path.resolve()
        try:
            checkpoint = torch.load(path, map_location="cpu", weights_only=False)
            state = checkpoint["model"] if isinstance(checkpoint, dict) and "model" in checkpoint else checkpoint
            model = role_model.RoleNet().cpu()
            model.load_state_dict(state, strict=True)
            model.eval()
            return model, path, checkpoint
        except Exception as exc:
            failures.append(f"{path.name}: {type(exc).__name__}: {exc}")
    raise SystemExit("no compatible RoleNet checkpoint found\n" + "\n".join(failures))


def iter_rows(data_dir: Path):
    paths = sorted(p for p in data_dir.glob("*.jsonl") if p.is_file())
    if not paths:
        raise SystemExit(f"no JSONL corpus files found in {data_dir}")
    for path in paths:
        with path.open(encoding="utf-8") as handle:
            for line_no, line in enumerate(handle, 1):
                if not line.strip():
                    continue
                try:
                    yield path.stem, json.loads(line)
                except json.JSONDecodeError as exc:
                    raise RuntimeError(f"bad JSON: {path}:{line_no}: {exc}") from exc


def predict_roles(model, tokens: list[dict]) -> list[str | None]:
    base = role_model.weak_base_roles(tokens)
    feats = [role_model.feat_token(token, base_role) for token, base_role in zip(tokens, base)]
    dummy_labels = [0] * len(tokens)
    batch, _, mask = role_model.collate([(feats, dummy_labels, "", "web")], torch.device("cpu"))
    with torch.no_grad():
        pred = model(batch, mask).argmax(-1)[0, : len(tokens)].tolist()
    return [role_model.I2ROLE[index] for index in pred]


def safe_cell(value, limit: int | None = None) -> str:
    text = str(value).replace("\t", " ").replace("\r", " ").replace("\n", " ")
    if limit and len(text) > limit:
        return text[: max(0, limit - 1)] + "…"
    return text


def pct(n: int, d: int) -> str:
    return f"{(100.0 * n / d):.2f}%" if d else "n/a"


def prf(confusion: Counter, role: str):
    tp = confusion[(role, role)]
    fp = sum(v for (gold, pred), v in confusion.items() if pred == role and gold != role)
    fn = sum(v for (gold, pred), v in confusion.items() if gold == role and pred != role)
    precision = tp / (tp + fp) if tp + fp else 0.0
    recall = tp / (tp + fn) if tp + fn else 0.0
    f1 = 2 * precision * recall / (precision + recall) if precision + recall else 0.0
    return tp, fp, fn, precision, recall, f1


def compare(model, data_dir: Path):
    overall = Counter()
    by_source = defaultdict(Counter)
    confusion = Counter()
    sentence_rows = []
    mismatches = []

    for source_file, row in iter_rows(data_dir):
        tokens = row.get("analysis", {}).get("tokens", [])
        if not tokens:
            continue
        predictions = predict_roles(model, tokens)
        source = row.get("source", {}).get("key") or source_file
        sent_id = row.get("source", {}).get("sent_id", "")
        text = row.get("text", "")
        source_url = row.get("source", {}).get("raw_file", "")

        comparable = correct = ambiguous = 0
        for token, pred in zip(tokens, predictions):
            gold = token.get("role")
            if gold == "AMBIG":
                ambiguous += 1
                continue
            gold_norm = gold if gold is not None else "NONE"
            pred_norm = pred if pred is not None else "NONE"
            comparable += 1
            confusion[(gold_norm, pred_norm)] += 1
            if gold_norm == pred_norm:
                correct += 1
            else:
                mismatches.append(
                    (
                        source,
                        sent_id,
                        token.get("id", ""),
                        token.get("text", ""),
                        token.get("pos", ""),
                        token.get("deprel", ""),
                        gold_norm,
                        pred_norm,
                        text,
                        source_url,
                    )
                )

        exact = comparable > 0 and correct == comparable
        overall["sentences"] += 1
        overall["tokens"] += len(tokens)
        overall["comparable"] += comparable
        overall["correct"] += correct
        overall["ambiguous"] += ambiguous
        overall["exact"] += int(exact)
        src = by_source[source]
        src["sentences"] += 1
        src["tokens"] += len(tokens)
        src["comparable"] += comparable
        src["correct"] += correct
        src["ambiguous"] += ambiguous
        src["exact"] += int(exact)
        sentence_rows.append(
            (
                source,
                sent_id,
                len(tokens),
                comparable,
                correct,
                pct(correct, comparable),
                "PASS" if exact else "DIFF",
                text,
                source_url,
            )
        )

    sentence_rows.sort(key=lambda r: (0 if r[6] == "DIFF" else 1, float(r[5][:-1]) if r[5] != "n/a" else 101, r[0], r[1]))
    return overall, by_source, confusion, sentence_rows, mismatches


def build_report(model_path: Path, checkpoint, overall, by_source, confusion, sentence_rows, mismatches) -> str:
    cfg = checkpoint.get("config", {}) if isinstance(checkpoint, dict) else {}
    metrics = checkpoint.get("metrics", {}) if isinstance(checkpoint, dict) else {}
    lines = [
        "SentenceLab Web Corpus: Original UD vs Current Model Comparison",
        "================================================================",
        f"MODEL\t{model_path.relative_to(ROOT) if ROOT in model_path.parents else model_path}",
        f"MODEL_CONFIG\t{json.dumps(cfg, ensure_ascii=False, sort_keys=True)}",
        f"CHECKPOINT_VERSION\t{metrics.get('version', 'unknown')}",
        f"SENTENCES\t{overall['sentences']}",
        f"TOKENS_TOTAL\t{overall['tokens']}",
        f"TOKENS_COMPARED\t{overall['comparable']}",
        f"TOKENS_CORRECT\t{overall['correct']}",
        f"TOKENS_AMBIG_EXCLUDED\t{overall['ambiguous']}",
        f"TOKEN_ACCURACY\t{pct(overall['correct'], overall['comparable'])}",
        f"SENTENCE_EXACT\t{overall['exact']}/{overall['sentences']} ({pct(overall['exact'], overall['sentences'])})",
        "",
        "[TABLE 1] Source summary",
        "SOURCE\tSENTENCES\tTOKENS\tCOMPARED\tCORRECT\tTOKEN_ACC\tEXACT_SENT\tEXACT_RATE\tAMBIG_EXCLUDED",
    ]
    for source in sorted(by_source):
        s = by_source[source]
        lines.append(
            "\t".join(
                map(
                    str,
                    [
                        source,
                        s["sentences"],
                        s["tokens"],
                        s["comparable"],
                        s["correct"],
                        pct(s["correct"], s["comparable"]),
                        s["exact"],
                        pct(s["exact"], s["sentences"]),
                        s["ambiguous"],
                    ],
                )
            )
        )

    lines += [
        "",
        "[TABLE 2] Per-role precision / recall / F1",
        "ROLE\tTP\tFP\tFN\tPRECISION\tRECALL\tF1",
    ]
    for role in ROLE_NAMES:
        tp, fp, fn, precision, recall, f1 = prf(confusion, role)
        lines.append(f"{role}\t{tp}\t{fp}\t{fn}\t{precision:.4f}\t{recall:.4f}\t{f1:.4f}")

    lines += [
        "",
        "[TABLE 3] Confusion matrix (rows=ORIGINAL/GOLD, columns=MODEL)",
        "GOLD\\PRED\t" + "\t".join(ROLE_NAMES),
    ]
    for gold in ROLE_NAMES:
        lines.append(gold + "\t" + "\t".join(str(confusion[(gold, pred)]) for pred in ROLE_NAMES))

    lines += [
        "",
        "[TABLE 4] Sentence-by-sentence comparison (DIFF first)",
        "SOURCE\tSENT_ID\tTOKENS\tCOMPARED\tCORRECT\tACCURACY\tSTATUS\tTEXT\tORIGINAL_URL",
    ]
    for row in sentence_rows:
        source, sent_id, tokens, compared, correct, accuracy, status, text, url = row
        lines.append(
            f"{safe_cell(source)}\t{safe_cell(sent_id)}\t{tokens}\t{compared}\t{correct}\t{accuracy}\t{status}\t{safe_cell(text, 180)}\t{safe_cell(url)}"
        )

    lines += [
        "",
        "[TABLE 5] Every mismatched token",
        "SOURCE\tSENT_ID\tTOKEN_ID\tTOKEN\tPOS\tUD_REL\tORIGINAL_ROLE\tMODEL_ROLE\tSENTENCE\tORIGINAL_URL",
    ]
    for source, sent_id, token_id, token, pos, deprel, gold, pred, text, url in mismatches:
        lines.append(
            "\t".join(
                [
                    safe_cell(source),
                    safe_cell(sent_id),
                    safe_cell(token_id),
                    safe_cell(token),
                    safe_cell(pos),
                    safe_cell(deprel),
                    safe_cell(gold),
                    safe_cell(pred),
                    safe_cell(text, 180),
                    safe_cell(url),
                ]
            )
        )

    lines += [
        "",
        "NOTES",
        "- ORIGINAL_ROLE is SentenceLab's canonical S/V/O/C/M projection of the upstream UD gold dependency parse.",
        "- MODEL_ROLE is produced independently by the selected SentenceLab neural RoleNet checkpoint.",
        "- Gold AMBIG tokens are excluded from accuracy and listed only in aggregate counts.",
        "- NONE normally corresponds to punctuation / intentionally unlabeled tokens.",
        "",
    ]
    return "\n".join(lines)


def self_test() -> None:
    confusion = Counter({("S", "S"): 8, ("S", "O"): 2, ("O", "O"): 7, ("O", "S"): 1})
    tp, fp, fn, precision, recall, f1 = prf(confusion, "S")
    assert (tp, fp, fn) == (8, 1, 2)
    assert round(precision, 4) == 0.8889
    assert round(recall, 4) == 0.8
    assert 0.84 < f1 < 0.85
    assert pct(9, 10) == "90.00%"
    print("comparison self-test: ok")


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--data-dir", default=str(DATA_DIR))
    parser.add_argument("--model", default=None)
    parser.add_argument("--out", default=str(DEFAULT_OUT))
    parser.add_argument("--self-test", action="store_true")
    args = parser.parse_args()

    if args.self_test:
        self_test()
        return

    torch.set_num_threads(4)
    model, model_path, checkpoint = load_latest_compatible_model(args.model)
    overall, by_source, confusion, sentence_rows, mismatches = compare(model, Path(args.data_dir))
    if overall["sentences"] == 0 or overall["comparable"] == 0:
        raise SystemExit("comparison produced no comparable data")

    report = build_report(model_path, checkpoint, overall, by_source, confusion, sentence_rows, mismatches)
    out = Path(args.out)
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text(report, encoding="utf-8", newline="\n")
    print(f"model={model_path.name}")
    print(f"sentences={overall['sentences']} compared_tokens={overall['comparable']} correct={overall['correct']} accuracy={pct(overall['correct'], overall['comparable'])}")
    print(f"exact_sentences={overall['exact']} mismatched_tokens={len(mismatches)}")
    print(f"wrote {out}")


if __name__ == "__main__":
    main()
