let keyCache;
const enc=new TextEncoder();
function cors(origin,env){const allowed=String(env.ALLOWED_ORIGINS||'').split(',').map(x=>x.trim());const ok=origin&&allowed.includes(origin);return {'Access-Control-Allow-Origin':ok?origin:'null','Vary':'Origin','Access-Control-Allow-Methods':'GET,HEAD,OPTIONS','Access-Control-Allow-Headers':'Content-Type'}}
function b64(s){const b=atob(s.trim()),u=new Uint8Array(b.length);for(let i=0;i<b.length;i++)u[i]=b.charCodeAt(i);return u}
async function aes(env){return keyCache||(keyCache=crypto.subtle.importKey('raw',b64(env.R2_AES_KEY_B64),'AES-GCM',false,['decrypt']))}
function mime(k){return k.endsWith('.jpg')?'image/jpeg':k.endsWith('.png')?'image/png':k.endsWith('.webp')||k.startsWith('220/')?'image/webp':'application/octet-stream'}
export default{async fetch(req,env){const u=new URL(req.url),origin=req.headers.get('Origin'),h=cors(origin,env);if(req.method==='OPTIONS')return new Response(null,{headers:h});if(!['GET','HEAD'].includes(req.method))return new Response('Method not allowed',{status:405,headers:h});
if(u.pathname==='/manifest'){const o=await env.ASSETS.get('manifest.json');if(!o)return new Response('Not found',{status:404,headers:h});return new Response(req.method==='HEAD'?null:o.body,{headers:{...h,'Content-Type':'application/json; charset=utf-8','Cache-Control':'no-store'}})}
let download=false,key;if(u.pathname.startsWith('/download/')){download=true;key=decodeURIComponent(u.pathname.slice(10))}else if(u.pathname.startsWith('/asset/'))key=decodeURIComponent(u.pathname.slice(7));else return new Response('Not found',{status:404,headers:h});
if(key.includes('..')||key.startsWith('/'))return new Response('Bad path',{status:400,headers:h});if(key.startsWith('220/')&&download)return new Response('220 download disabled',{status:403,headers:h});const o=await env.ASSETS.get(key);if(!o)return new Response('Not found',{status:404,headers:h});
if(key.startsWith('220/')){const raw=new Uint8Array(await o.arrayBuffer());if(raw.length<29)return new Response('Bad encrypted object',{status:500,headers:h});const iv=raw.slice(0,12),ct=raw.slice(12),aad=key.replace(/\.enc$/,'');let plain;try{plain=await crypto.subtle.decrypt({name:'AES-GCM',iv,additionalData:enc.encode(aad)},await aes(env),ct)}catch{return new Response('Decrypt failed',{status:500,headers:h})}return new Response(req.method==='HEAD'?null:plain,{headers:{...h,'Content-Type':'image/webp','Content-Disposition':'inline','Cache-Control':'private, no-store'}})}
const headers={...h,'Content-Type':mime(key),'Cache-Control':'public, max-age=86400'};if(download){const m=key.match(/^(218|219)\/(\d{3})\.(jpg|webp)$/);headers['Content-Disposition']=`attachment; filename="${m?`${m[1]}_${m[2]}.${m[3]}`:'download'}"`}return new Response(req.method==='HEAD'?null:o.body,{headers})}}
};
